---
global:
  config: []
  policy: ~
  working_dir: ".sigma-dir"
analyze:
  disable_checkers: []
  checker_severity_overrides: []
  format: JSON
  output: sigma-results.json
  ignore_scm: false
  follow_symlinks: false
  ignore_hidden_files: false
  input: ~
  make_paths_absolute: false
  repo_root: ~
  paths: []
